language: r
sudo: required
pandoc_version: 1.19.2.1

r_packages:
  - git2r
  - bookdown

cache:
  packages: true

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

